server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personnel?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    # 格式化全局时间字段 年-月-天
    date-format: yyyy-MM-dd
    # 指定时间区域类型 东8区时区 既北京时间
    time-zone: GMT+8
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 1958810573@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: zhtctqbahoefciab
    # 端口号465或587
    port: 587 
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  thymeleaf:
    cache: false #关闭缓存
    mode: HTML5 #设置模板类型
    encoding: utf-8  #设置编码
mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  not-empty: true
logging:
  level:
    com.coding.demo.mapper: debug  
    
# pagehelper   
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
#jodconverter:
#  local:
#    enabled: true
#    # 设置LibreOffice主目录
#    #    office-home: /opt/libreoffice6.4
#    office-home: D:/openOffice
#    # 开启多个LibreOffice进程，每个端口对应一个进程
#    portNumbers: 9080,9081,9089
#    # LibreOffice进程重启前的最大进程数
#    maxTasksPerProcess: 100

#jodconverter

jodconverter:
  local:
    enabled: true
    office-home: C:\Program Files (x86)\OpenOffice 4
    max-tasks-per-process: 10
    port-numbers: 8100
    
    #thymeleaf 模板解析器属性
